# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glaccounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "can_guarantee",
                    models.BooleanField(
                        default=True,
                        help_text="Can this savings account be used as collateral for a loan?",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saving_types",
                        to="glaccounts.glaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Account Type",
                "verbose_name_plural": "Savings Account Types",
                "ordering": ["-created_at"],
            },
        ),
    ]
