# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanproducts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "repayment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "calculation_mode",
                    models.CharField(
                        choices=[
                            ("fixed_term", "Fixed Term"),
                            ("fixed_payment", "Fixed Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("term_months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "repayment_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("projection_snapshot", models.JSONField(default=dict)),
                (
                    "self_guaranteed_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ready for Amendment", "Ready for Amendment"),
                            ("Amended", "Amended"),
                            ("In Progress", "In Progress"),
                            ("Ready for Submission", "Ready for Submission"),
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Disbursed", "Disbursed"),
                            ("Declined", "Declined"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Ready for Amendment",
                        max_length=30,
                    ),
                ),
                ("amendment_note", models.TextField(blank=True, null=True)),
                ("admin_created", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="loanproducts.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
