# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import loanpayments.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanaccounts", "0001_initial"),
        ("paymentaccounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "callback_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                            ("REVERSED", "REVERSED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "mpesa_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "repayment_type",
                    models.CharField(
                        choices=[
                            ("Regular Repayment", "Regular Repayment"),
                            ("Partial Payment", "Partial Payment"),
                            ("Early Settlement", "Early Settlement"),
                            ("Penalty Payment", "Penalty Payment"),
                            ("Loan Clearance", "Loan Clearance"),
                            ("Interest Only", "Interest Only"),
                            ("Mpesa STK Push", "Mpesa STK Push"),
                        ],
                        default="Regular Repayment",
                        max_length=70,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        help_text="The main status of the transaction",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_code",
                    models.CharField(
                        default=loanpayments.utils.generate_loan_payment_code,
                        editable=False,
                        max_length=76,
                        unique=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False, editable=False)),
                ("balance_updated", models.BooleanField(default=False, editable=False)),
                ("accounting_error", models.TextField(blank=True, null=True)),
                (
                    "loan_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_payments",
                        to="loanaccounts.loanaccount",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_payments",
                        to="paymentaccounts.paymentaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Payment",
                "verbose_name_plural": "Loan Payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["loan_account", "payment_date"],
                        name="loanpayment_loan_ac_b89048_idx",
                    ),
                    models.Index(
                        fields=["paid_by", "payment_date"],
                        name="loanpayment_paid_by_6c628b_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="loanpayment_referen_ced3f2_idx"
                    ),
                ],
            },
        ),
    ]
