# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.core.validators
import django.db.models.deletion
import savingsdeposits.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paymentaccounts", "0001_initial"),
        ("savings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Amount must be greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[
                            ("Opening Balance", "Opening Balance"),
                            ("Payroll Deduction", "Payroll Deduction"),
                            ("Individual Deposit", "Individual Deposit"),
                            ("Dividend Deposit", "Dividend Deposit"),
                            ("Other", "Other"),
                        ],
                        default="Individual Deposit",
                        max_length=100,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        help_text="The main status of the transaction",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "identity",
                    models.CharField(
                        default=savingsdeposits.utils.generate_identity,
                        editable=False,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False, editable=False)),
                ("balance_updated", models.BooleanField(default=False, editable=False)),
                ("accounting_error", models.TextField(blank=True, null=True)),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "callback_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                            ("REVERSED", "REVERSED"),
                        ],
                        default="PENDING",
                        help_text="The status of the Mpesa payment. Does not override the transaction status.",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status_description",
                    models.CharField(
                        blank=True,
                        help_text="The description of the Mpesa payment status.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        help_text="The confirmation code of the Mpesa payment.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_account",
                    models.CharField(
                        blank=True,
                        help_text="The payment account of the Mpesa payment.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date of the Mpesa payment.",
                        null=True,
                    ),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="The receipt number of the Mpesa payment.",
                        max_length=2550,
                        null=True,
                    ),
                ),
                (
                    "mpesa_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The phone number of the Mpesa payment.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "deposited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="savings_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="savings_deposits",
                        to="paymentaccounts.paymentaccount",
                    ),
                ),
                (
                    "savings_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="savings.savingsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savings Deposit",
                "verbose_name_plural": "Savings Deposits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["savings_account", "created_at"],
                        name="savingsdepo_savings_7c6340_idx",
                    ),
                    models.Index(
                        fields=["deposited_by", "created_at"],
                        name="savingsdepo_deposit_efa7ae_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="savingsdepo_referen_b0a2d8_idx"
                    ),
                ],
            },
        ),
    ]
