# Generated by Django 6.0.1 on 2026-06-25 10:38

import django.db.models.deletion
import paymentaccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentaccounts', '0001_initial'),
        ('savingsdeposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsdeposit',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=paymentaccounts.models.get_default_payment_method, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_deposits', to='paymentaccounts.paymentaccount'),
        ),
    ]
