# Generated by Django 6.0.1 on 2026-05-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="payroll_number",
        ),
    ]
