# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import paymentaccounts.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glaccounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="I&M Bank, M-Pesa, etc. Just a short name for the member to reference",
                        max_length=1000,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=paymentaccounts.utils.generate_payment_account_code,
                        editable=False,
                        help_text="Unique code for the payment account",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_accounts",
                        to="glaccounts.glaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Account",
                "verbose_name_plural": "Payment Accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
