# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuarantorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_eligible", models.BooleanField(default=False)),
                ("eligibility_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_active_guarantees",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Max number of loans this member can guarantee",
                    ),
                ),
                (
                    "max_guarantee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "committed_guarantee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guarantor Profile",
                "verbose_name_plural": "Guarantor Profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
