# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.core.validators
import django.db.models.deletion
import loandisbursements.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanaccounts", "0001_initial"),
        ("paymentaccounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDisbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Amount must be greater than 0"
                            )
                        ],
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "disbursement_type",
                    models.CharField(
                        choices=[("Principal", "Principal"), ("Refill", "Refill")],
                        default="Principal",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(
                        default=loandisbursements.utils.generate_loan_disbursement_code,
                        editable=False,
                        max_length=46,
                        unique=True,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False, editable=False)),
                ("balance_updated", models.BooleanField(default=False, editable=False)),
                ("accounting_error", models.TextField(blank=True, null=True)),
                (
                    "disbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="loanaccounts.loanaccount",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_disbursements",
                        to="paymentaccounts.paymentaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Disbursement",
                "verbose_name_plural": "Loan Disbursements",
                "ordering": ["-created_at"],
            },
        ),
    ]
