# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.core.validators
import django.db.models.deletion
import feepayments.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeaccounts", "0001_initial"),
        ("paymentaccounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "callback_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                            ("REVERSED", "REVERSED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "mpesa_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Amount must be greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "code",
                    models.CharField(
                        default=feepayments.utils.generate_fee_payment_code,
                        editable=False,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False, editable=False)),
                ("balance_updated", models.BooleanField(default=False, editable=False)),
                ("accounting_error", models.TextField(blank=True, null=True)),
                (
                    "fee_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_payments",
                        to="feeaccounts.feeaccount",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_payments",
                        to="paymentaccounts.paymentaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Payment",
                "verbose_name_plural": "Fee Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fee_account", "created_at"],
                        name="feepayments_fee_acc_f019a3_idx",
                    ),
                    models.Index(
                        fields=["paid_by", "created_at"],
                        name="feepayments_paid_by_a9e3ea_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="feepayments_referen_35ef64_idx"
                    ),
                ],
            },
        ),
    ]
