# Generated by Django 6.0.1 on 2026-06-25 10:38

import django.db.models.deletion
import paymentaccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feepayments', '0001_initial'),
        ('paymentaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.ForeignKey(default=paymentaccounts.models.get_default_payment_method, on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='paymentaccounts.paymentaccount'),
        ),
    ]
