# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import existingloans.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glaccounts", "0001_initial"),
        ("paymentaccounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExistingLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default=existingloans.utils.generate_existing_loan_account_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The outstanding balance at the point of adoption. It is assumed that the interest and processing fee have been included in this amount.",
                        max_digits=15,
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_interest_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The total interest paid on the loan. Added manually during payment",
                        max_digits=15,
                    ),
                ),
                (
                    "total_amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_penalties_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The total penalties paid on the loan. Added manually during payment",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Closed", "Closed"),
                            ("Defaulted", "Defaulted"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("posted_to_gl", models.BooleanField(default=False, editable=False)),
                ("balance_updated", models.BooleanField(default=False, editable=False)),
                ("accounting_error", models.TextField(blank=True, null=True)),
                (
                    "gl_interest_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="existing_loans_interest_income",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "gl_penalty_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="existing_loans_penalty_income",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "gl_principal_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="existing_loans_principal_assets",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="existing_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="existing_loans_payments",
                        to="paymentaccounts.paymentaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Existing Loan",
                "verbose_name_plural": "Existing Loans",
                "ordering": ["-created_at"],
            },
        ),
    ]
