# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.db.models.deletion
import loanaccounts.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loanapplications", "0001_initial"),
        ("loanproducts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default=loanaccounts.utils.generate_loan_account_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("principal", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("last_interest_calulation", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Funded", "Funded"),
                            ("Closed", "Closed"),
                            ("Defaulted", "Defaulted"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "total_interest_accrued",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_principal_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "projection_snapshot",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_account",
                        to="loanapplications.loanapplication",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="loanproducts.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Account",
                "verbose_name_plural": "Loan Accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
