# Generated by Django 6.0.1 on 2026-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='total_loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
