# Generated by Django 6.0.1 on 2026-05-07 18:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("glaccounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                (
                    "interest_method",
                    models.CharField(
                        choices=[
                            ("Flat", "Flat-rate"),
                            ("Reducing", "Reducing (Diminishing) Balance"),
                        ],
                        default="Reducing",
                        help_text="Defines how interest is calculated (Flat-rate or Reducing Balance).",
                        max_length=20,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "interest_period",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Annually", "Annually"),
                        ],
                        default="Monthly",
                        help_text="How interest is calculated",
                        max_length=50,
                    ),
                ),
                (
                    "calculation_schedule",
                    models.CharField(
                        choices=[
                            ("Fixed", "Fixed Calendar (e.g., 1st of month)"),
                            ("Relative", "Relative to Loan Start Date"),
                            ("Flexible", "Custom/Flexible Schedule"),
                        ],
                        default="Relative",
                        help_text="Defines when interest is calculated (fixed calendar, loan start date, or custom).",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gl_interest_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_interest_income",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "gl_penalty_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_penalty_income",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "gl_principal_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_principal_assets",
                        to="glaccounts.glaccount",
                    ),
                ),
                (
                    "gl_processing_fee_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_processing_fee_income",
                        to="glaccounts.glaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Product",
                "verbose_name_plural": "Loan Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
